# render.yaml
services:
  - name: my-telegram-bot
    build:
      docker: Dockerfile
    envVars:
      - name: BOT_TOKEN
        value: 7765223935:AAE1PSF2JzymyDyWv_B4dqgH4hvQYjfTPaU
   
      - name: INSTAGRAM_USERNAME
        value: mtkh13o
      - name: INSTAGRAM_PASSWORD
        value: 191275Mm
